# Lab-5 행렬 자르기,합치기 등 기본연습

In [3]:
import tensorflow as tf
import functions

In [2]:
import tensorflow as tf
import functions

c1 = tf.constant([1, 3, 5, 7, 9, 0, 2, 4, 6, 8])
c2 = tf.constant([1, 3, 5])
v1 = tf.constant([[1, 2, 3, 4, 5, 6], [7, 8, 9, 0, 1, 2],[11, 12, 13, 14, 15, 16]])
v2 = tf.constant([[1, 2, 3], [7, 8, 9]])

In [9]:
functions.showOperation(tf.slice(c1, [4], [1]))     

[9]


In [29]:
functions.showOperation(v1)

[[ 1  2  3  4  5  6]
 [ 7  8  9  0  1  2]
 [11 12 13 14 15 16]]


In [28]:
functions.showOperation(tf.slice(v1, [0,1], [3, 2]))  

[[ 2  3]
 [ 8  9]
 [12 13]]


In [33]:
functions.showOperation(tf.slice(v1, [0, 2], [3,-1]))

[[ 3  4  5  6]
 [ 9  0  1  2]
 [13 14 15 16]]


In [7]:
functions.showOperation(tf.split(0, 2, c1)) # [[1, 3, 5, 7, 9], [0, 2, 4, 6, 8]]
temp = tf.split(0, 2, c1)
functions.showOperation(temp[0])
functions.showOperation(temp[1])

[array([1, 3, 5, 7, 9], dtype=int32), array([0, 2, 4, 6, 8], dtype=int32)]
[1 3 5 7 9]
[0 2 4 6 8]


In [47]:
functions.showOperation(tf.split(0, 5, c1)) # [[1, 3], [5, 7], [9, 0], [2, 4], [6, 8]]

[array([1, 3], dtype=int32), array([5, 7], dtype=int32), array([9, 0], dtype=int32), array([2, 4], dtype=int32), array([6, 8], dtype=int32)]


In [52]:
functions.showOperation(tf.split(1, 3, v1)) # [[[1, 2, 3, 4, 5, 6]], [[7, 8, 9, 0, 1, 2]]]

[array([[ 1,  2],
       [ 7,  8],
       [11, 12]], dtype=int32), array([[ 3,  4],
       [ 9,  0],
       [13, 14]], dtype=int32), array([[ 5,  6],
       [ 1,  2],
       [15, 16]], dtype=int32)]


In [50]:
functions.showOperation(tf.split(0, 3, v1)) # [[[1, 2, 3], [7, 8, 9]], [[4, 5, 6], [0, 1, 2]]]

[array([[1, 2, 3, 4, 5, 6]], dtype=int32), array([[7, 8, 9, 0, 1, 2]], dtype=int32), array([[11, 12, 13, 14, 15, 16]], dtype=int32)]


In [51]:
functions.showOperation(tf.split(1, 2, v1)) # [[[1, 2, 3], [7, 8, 9]], [[4, 5, 6], [0, 1, 2]]]

[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [11, 12, 13]], dtype=int32), array([[ 4,  5,  6],
       [ 0,  1,  2],
       [14, 15, 16]], dtype=int32)]


In [53]:
functions.showOperation(tf.tile(c2, [3]))   # [1 3 5 1 3 5 1 3 5]
                                           # [[1 2 3 1 2 3] [7 8 9 7 8 9] [1 2 3 1 2 3] [7 8 9 7 8 9]]

[1 3 5 1 3 5 1 3 5]


In [54]:
functions.showOperation(tf.tile(v2, [2, 2]))

[[1 2 3 1 2 3]
 [7 8 9 7 8 9]
 [1 2 3 1 2 3]
 [7 8 9 7 8 9]]


In [58]:
functions.showOperation(tf.one_hot([0, 1, 2, 1], 3))
# [[ 0.  0.  0.  1.]
#  [ 0.  0.  0.  0.]
#  [ 0.  1.  0.  0.]]

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]


In [61]:
functions.showOperation(tf.one_hot([3, -1, 1], 4))

[[ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  1.  0.  0.]]


In [62]:
functions.showOperation(tf.concat(0, [c1, c2]))     # [1 3 5 7 9 0 2 4 6 8 1 3 5]

[1 3 5 7 9 0 2 4 6 8 1 3 5]


In [87]:
d1 = [1,2,3,4,5,6,7,8,9]
functions.showOperation(tf.one_hot(d1[:-1], len(d1), 1, 0,-1))

[[0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]
